services:
  pipeline-licitaciones:
    build: .
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - PLAYWRIGHT_SKIP_VALIDATE_HOST_REQUIREMENTS=true
    volumes:
      - ./data:/app/data
    networks:
      - pipeline-network

networks:
  pipeline-network:
    driver: bridge